### PR TITLE
llama2-local-model-with-qa-notebook-init

### PR DESCRIPTION
**Pull request by asabuncuoglu13**
- Added a new README for local model generation on MacOS.
- Added a Jupyter notebook as a local model use case.
- Created a subfolder system under the "scripts" folder: Local, Remote, HPC

### CODE REVIEW

**Comment by fedenanni** [comment]
@asabuncuoglu13 Wonderful - thanks a lot for this, I'm tagging @rchan26 as well so he doesn't miss this contribution.

It all looks good to me, I'll let Ryan merge it so i'm sure he doesn't miss my notification!

**Review by fedenanni — APPROVED** [review]

**Comment by rchan26** [comment]
thanks @asabuncuoglu13 (and @fedenanni for tagging). generally all looks good to me! but some minor points:

- I think maybe we should label this as running a quantised version of Llama? 
- another thing is we could maybe say that its possible to download quantised versions of Llama (and other models) on the Huggingface hub rather than having to quantising them yourself?
  - e.g. looks like we quantise a model to create a GGML file, but we could've taken it from [here](https://huggingface.co/TheBloke/LLaMa-7B-GGML/tree/main). In fact, [The Bloke](https://huggingface.co/TheBloke] has many quantised models on their page

**Comment by asabuncuoglu13** [comment]
All good points @rchan26! It adds a good value to the repository mentioning these ready-to-use models. But, while referring to downloading models from non-official channels, I think we should discuss the security caveats and copyright considerations. So, I will include another commit with these changes before merging.

**Comment by rchan26** [comment]
ah yes good point - worth adding a point about those caveats! thanks a lot @asabuncuoglu13 ! feel free to request another review after those changes and I'll have another look 🙂

**Comment by asabuncuoglu13** [comment]
@rchan26, I added the HF-Hub download link and possible security issues and mitigations.

**Review by rchan26 — APPROVED** [review]
looks good @asabuncuoglu13 - thanks a lot for this!

**Pull request merged**
